### ISSUE TITLE
Error with botocore.vendored when calling lex-bot-get-schema

### ISSUE THREAD

**Issue by davidfsmith** [aws-samples/amazon-lex-bot-deploy#5]
* amazon-lex-bot-deploy version: 0.1.7
* Python version: 3.8
* Operating System: OSX

### Description

Attempting to export the schema for a demo chat bot and received an error from `botocore.vendored`

### What I Did

```
lex-bot-get-schema --region eu-west-1 --version 1 --lex-bot-name  chatbot`
ERROR:amazon_lex_bot_deploy.amazon_lex_bot_deploy:module 'botocore.vendored.requests' has no attribute 'get'
```

**Note:** `requests` has been deprecated from `botocore.vendored` as per [this](https://aws.amazon.com/blogs/developer/removing-the-vendored-version-of-requests-from-botocore/) blog post.

**Comment by schadem** [comment]
Fixed and pushed to PyPI as version 0.1.8.
Thx, @davidfsmith !
