### ISSUE TITLE
Unable to import Lex bots with fallbackIntent and clarification prompts unchecked in the Error Handling section of the bot

### ISSUE THREAD

**Issue by agnel0410** [aws-samples/amazon-lex-bot-deploy#7]
“
INFO:amazon_lex_bot_deploy.amazon_lex_bot_deploy:deployed all intents
ERROR:__main__:'clarificationPrompt'
Traceback (most recent call last):
  File "./build-lexbots.py", line 131, in <module>
    check=True)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['lex-bot-deploy', '-s', './build/lexbots/YesNoWithFallback.json']' returned non-zero exit status 1.
ERROR: could not deploy ./build/lexbots/YesNoWithFallback.json

**Comment by schadem** [comment]
Resolved. Checks now if clarificationPrompt exists in the schema and if not does not try to send it to the put_bot command.
Thx for pointing out the issue!
